version: "3.3"

services:
  ticker:
    build: .
    devices:
      - "/dev/mem:/dev/mem"
    privileged: true
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/code/config:ro
