version: "3.8"

services:
  ticker: &default
    build:
      context: .
    devices:
      - "/dev/mem:/dev/mem"
    privileged: true
    restart: always
    env_file:
      - ./settings.env
    volumes:
      - .:/code

  pytest:
    <<: *default
    command: "./run_tests.sh"
