# render-duration: 8
[display]
rows = 16
cols = 32
chain_length = 5
default_scale = 1
brightness = 60

[transitions]
default = "cut"

[[playlist.section]]
mode = "slideshow"
loop_count = 1
hold_time = 7.0

[[playlist.section.widget]]
type = "gif"
path = "../../../config/assets/phoenix_transparent.gif"
fit = "pillarbox"
image_align = "left"
text = "Scrolling behind the phoenix!"
text_align = "scroll"
font_color = [200, 200, 255]
play_count = 5
scroll_speed_ms = 25
