# render-duration: 8
[display]
rows = 16
cols = 32
chain = 5
default_scale = 1
brightness = 60

[transitions]
default = "cut"

[[playlist.section]]
mode = "swap"
loop_count = 1
hold_time = 7.0

[[playlist.section.widget]]
type = "gif"
path = "../../../config/assets/pika_wave_transparent.gif"
fit = "pillarbox"
image_align = "left"
text = "Welcome to the show!"
text_align = "scroll_over"
font_color = [225, 48, 108]
gif_loops = 0
scroll_speed_ms = 25
