# render-duration: 6
[display]
rows = 16
cols = 32
chain_length = 5
default_scale = 1
brightness = 60

[transitions]
default = "cut"

[[playlist.section]]
mode = "swap"
loop_count = 1
hold_time = 5.0

[[playlist.section.widget]]
type = "gif"
path = "../../../config/assets/pika_wave_transparent.gif"
fit = "pillarbox"
image_align = "left"
text = "hi friend"
text_align = "right"
font_color = "rainbow"
animation = "typewriter"
play_count = 0
