# render-duration: 5
[display]
rows = 16
cols = 32
chain_length = 5
default_scale = 1
brightness = 60

[transitions]
default = "cut"

[[playlist.section]]
mode = "swap"
loop_count = 1
hold_time = 4.0

[[playlist.section.widget]]
type = "image"
path = "../../../config/assets/moon-transparent.png"
fit = "pillarbox"
image_align = "center"
hold_time = 4.0
