# render-duration: 5
[display]
rows = 16
cols = 32
chain = 5
default_scale = 1
brightness = 60

[transitions]
default = "cut"

[[playlist.section]]
mode = "swap"
loop_count = 1
hold_time = 4.0

[[playlist.section.widget]]
type = "message"
text = "CAUTION"
font_color = [0, 0, 0]
bg_color = [255, 220, 0]
