"""led-ticker: Asyncio LED matrix display for news, weather, crypto, and more."""

try:
    # Generated by hatch-vcs at build time (see pyproject [tool.hatch.build.hooks.vcs]).
    from led_ticker._version import __version__
except ImportError:  # raw source tree, not yet built
    __version__ = "0.0.0+unknown"
