"""GENERATED by tools/gen_emoji_pack.py — do not edit.

BMP (< U+10000) codepoints present in the emoji pack. The unicode
run scanner's regex builds at import time, so pack BMP emoji need
this static allowlist (astral emoji match by range)."""

PACK_BMP: str = '#*©®‼⁉™ℹ↔↕↖↗↘↙↩↪⌚⌛⌨⏏⏩⏪⏫⏬⏭⏮⏯⏰⏱⏲⏳⏸⏹⏺Ⓜ▪▫▶◀◻◼◽◾☂☃☄☎☑☔☕☘☝☠☢☣☦☪☮☯☸☹☺♀♂♈♉♊♋♌♍♎♏♐♑♒♓♟♠♣♥♦♨♻♾♿⚒⚓⚔⚕⚖⚗⚙⚛⚜⚠⚡⚧⚪⚫⚰⚱⚽⚾⛄⛎⛏⛑⛓⛔⛩⛪⛰⛱⛲⛳⛴⛵⛷⛸⛹⛺⛽✂✅✈✊✋✌✍✏✒✔✖✝✡✳✴❇❌❎❓❔❕❗❣➕➖➗➡➰➿⤴⤵⬅⬆⬇⬛⬜⭕〰〽㊗㊙'  # noqa: E501
