#!/usr/bin/env python3
"""Regenerate the `_FIRE_HIRES_PIXELS` constant in `pixel_emoji.py` from the
vendored Noto Emoji fire glyph.

The hi-res `:fire:` sprite is baked from the real Noto Emoji "fire" glyph
(U+1F525) rather than hand-authored, because a parametric flame read too much
like the `:droplet:` teardrop. Noto Emoji is © Google under the Apache License
2.0 — see `THIRD_PARTY_NOTICES.md`.

This script downsamples the 512×512 source PNG to 32×32 (Lanczos) and
alpha-thresholds it into the `(x, y, r, g, b)` pixel list, then prints the
literal for pasting into `src/led_ticker/pixel_emoji.py`. It is provenance
tooling (like `tools/derive_phoenix_assets.py`) — run it to reproduce the
committed constant, not at build time.

    uv run python tools/gen_fire_hires.py

Source: tools/assets/noto_emoji_u1f525.png (vendored from
https://github.com/googlefonts/noto-emoji, png/512/emoji_u1f525.png).
"""

from pathlib import Path

from PIL import Image

_SRC = Path(__file__).parent / "assets" / "noto_emoji_u1f525.png"
_SIZE = 32
_ALPHA = 110  # keep pixels at least this opaque after downsample


def generate() -> list[tuple[int, int, int, int, int]]:
    img = (
        Image.open(_SRC)
        .convert("RGBA")
        .resize((_SIZE, _SIZE), Image.Resampling.LANCZOS)
    )
    px = img.load()
    assert px is not None
    out: list[tuple[int, int, int, int, int]] = []
    for y in range(_SIZE):
        for x in range(_SIZE):
            r, g, b, a = px[x, y]
            if a >= _ALPHA:
                out.append((x, y, r, g, b))
    return out


def main() -> None:
    pixels = generate()
    print(
        f"# {len(pixels)} px — regenerated by tools/gen_fire_hires.py from "
        "the Noto Emoji fire glyph (Apache 2.0; see THIRD_PARTY_NOTICES.md)"
    )
    print("_FIRE_HIRES_PIXELS: tuple[tuple[int, int, int, int, int], ...] = (")
    for x, y, r, g, b in pixels:
        print(f"    ({x}, {y}, {r}, {g}, {b}),")
    print(")")


if __name__ == "__main__":
    main()
