#!/usr/bin/env python3
"""Regenerate `src/led_ticker/_curated_noto_hires.py` — Noto-baked hi-res
sprites for the curated slugs James chose to adopt (2026-07-21 review:
"all recs" — the weather six + moon + droplet; fog/email/flower/bunny/taco
stay hand-authored).

These are CURATED slugs (lowres 8×8 stays hand-drawn; unicode aliases and
`:slug:` names unchanged) — only the hi-res sprite is a Noto bake, exactly
like `:fire:`. Noto Emoji is © Google, Apache License 2.0 — see
`THIRD_PARTY_NOTICES.md`.

    uv run python tools/gen_curated_noto_hires.py

Fetches (cached in the gitignored tools/assets/_noto_cache/) and applies the
proven fire recipe: Lanczos 32×32, alpha >= 110.
"""

import urllib.request
from pathlib import Path

from PIL import Image

_ROOT = Path(__file__).parent
_CACHE = _ROOT / "assets" / "_noto_cache"
_OUT = _ROOT.parent / "src" / "led_ticker" / "_curated_noto_hires.py"
_NOTO = "https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/512/emoji_u{cp:04x}.png"
_ALPHA = 110

# slug -> Noto source codepoint (James's adoption list, 2026-07-21)
ADOPTED: dict[str, int] = {
    "sun": 0x2600,
    "cloud": 0x2601,
    "partly_cloudy": 0x26C5,
    "rain": 0x1F327,
    "snow": 0x2744,
    "thunder": 0x26C8,
    "moon": 0x1F319,
    "droplet": 0x1F4A7,
}


def _fetch(cp: int) -> Path:
    _CACHE.mkdir(exist_ok=True)
    dst = _CACHE / f"emoji_u{cp:04x}.png"
    if not dst.exists():
        with urllib.request.urlopen(_NOTO.format(cp=cp), timeout=60) as r:
            dst.write_bytes(r.read())
    return dst


def _bake(png: Path) -> list[tuple[int, int, int, int, int]]:
    img = Image.open(png).convert("RGBA").resize((32, 32), Image.Resampling.LANCZOS)
    px = img.load()
    assert px is not None
    return [
        (x, y, *px[x, y][:3])
        for y in range(32)
        for x in range(32)
        if px[x, y][3] >= _ALPHA
    ]


def main() -> None:
    lines = [
        '"""GENERATED by tools/gen_curated_noto_hires.py — do not edit.',
        "",
        "Noto-baked 32x32 hi-res sprites for adopted CURATED slugs (the",
        "weather six + moon + droplet). Overlaid onto HIRES_REGISTRY at",
        "assembly; lowres/aliases/variants unchanged. Noto Emoji is (c)",
        'Google, Apache 2.0 - see THIRD_PARTY_NOTICES.md."""',
        "",
        "NOTO_HIRES: dict[str, tuple[tuple[int, int, int, int, int], ...]] = {",
    ]
    for slug, cp in sorted(ADOPTED.items()):
        pixels = _bake(_fetch(cp))
        lines.append(f'    "{slug}": (')
        for px in pixels:
            lines.append(f"        {px!r},")
        lines.append("    ),")
    lines.append("}")
    _OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {_OUT} ({len(ADOPTED)} sprites)")


if __name__ == "__main__":
    main()
