#!/usr/bin/env python3
"""Build the committed emoji-pack artifacts from the manifest:

    uv run python tools/gen_emoji_pack.py

Reads tools/assets/emoji_manifest.txt, fetches each Noto Emoji PNG
(png/512/emoji_uXXXX.png) into a gitignored cache (tools/assets/_noto_cache/),
applies the proven :fire: recipe (Lanczos 32×32, alpha >= 110), and writes:

- src/led_ticker/assets/emoji_pack.bin   (the pack)
- src/led_ticker/_emoji_pack_bmp.py      (generated BMP allowlist for the
                                          unicode-run scanner, which builds
                                          its regex at import time)

Noto Emoji is © Google, Apache License 2.0 — THIRD_PARTY_NOTICES.md.
Missing glyphs (404) are reported and SKIPPED (some CLDR entries have no
Noto file); the run summary lists them for manifest pruning.
"""

import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from led_ticker.emoji_pack import write_pack  # noqa: E402

_ROOT = Path(__file__).parent
_MANIFEST = _ROOT / "assets" / "emoji_manifest.txt"
_CACHE = _ROOT / "assets" / "_noto_cache"
_PACK_OUT = _ROOT.parent / "src" / "led_ticker" / "assets" / "emoji_pack.bin"
_BMP_OUT = _ROOT.parent / "src" / "led_ticker" / "_emoji_pack_bmp.py"
_NOTO = "https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/512/emoji_u{cp:04x}.png"
_ALPHA = 110


def _fetch(cp: int) -> Path | None:
    _CACHE.mkdir(exist_ok=True)
    dst = _CACHE / f"emoji_u{cp:04x}.png"
    if dst.exists():
        return dst
    try:
        with urllib.request.urlopen(_NOTO.format(cp=cp), timeout=60) as r:
            dst.write_bytes(r.read())
        return dst
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        # Non-404 HTTPError (5xx/429 etc.) falls through to the shared retry
        # below — it must NOT re-raise here, or the retry never fires.
    except urllib.error.URLError, TimeoutError:
        pass
    # Transient network hiccup (non-404 HTTPError / URLError / TimeoutError) —
    # retry once; a second failure propagates.
    time.sleep(1)
    with urllib.request.urlopen(_NOTO.format(cp=cp), timeout=60) as r:
        dst.write_bytes(r.read())
    return dst


def _bake(png: Path) -> list[tuple[int, int, int, int, int]]:
    img = Image.open(png).convert("RGBA").resize((32, 32), Image.Resampling.LANCZOS)
    px = img.load()
    assert px is not None
    return [
        (x, y, *px[x, y][:3])
        for y in range(32)
        for x in range(32)
        if px[x, y][3] >= _ALPHA
    ]


def main() -> None:
    entries = []
    skipped: list[str] = []
    lines = _MANIFEST.read_text().splitlines()
    total = len(lines)
    for i, line in enumerate(lines, 1):
        cp_s, slug = line.split("\t")
        cp = int(cp_s[2:], 16)
        png = _fetch(cp)
        if png is None:
            skipped.append(f"{cp_s} {slug}")
            continue
        pixels = _bake(png)
        if not pixels:
            skipped.append(f"{cp_s} {slug} (empty after threshold)")
            continue
        entries.append((slug, cp, pixels))
        if i % 100 == 0:
            print(
                f"...{i}/{total} fetched "
                f"({len(entries)} packed, {len(skipped)} skipped)"
            )
    _PACK_OUT.parent.mkdir(exist_ok=True)
    write_pack(entries, _PACK_OUT)
    bmp = "".join(sorted(chr(cp) for _, cp, _ in entries if cp < 0x10000))
    _BMP_OUT.write_text(
        '"""GENERATED by tools/gen_emoji_pack.py — do not edit.\n\n'
        "BMP (< U+10000) codepoints present in the emoji pack. The unicode\n"
        "run scanner's regex builds at import time, so pack BMP emoji need\n"
        'this static allowlist (astral emoji match by range)."""\n\n'
        f"PACK_BMP: str = {bmp!r}  # noqa: E501\n"
    )
    print(
        f"packed {len(entries)} sprites -> {_PACK_OUT} "
        f"({_PACK_OUT.stat().st_size / 1e6:.2f} MB); "
        f"{len(bmp)} BMP chars -> {_BMP_OUT}"
    )
    if skipped:
        print(f"skipped {len(skipped)} (no Noto glyph / empty):")
        for s in skipped:
            print("  ", s)


if __name__ == "__main__":
    main()
